# Generated by Django 6.0.4 on 2026-08-17 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickentry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualentry',
            name='unmapped_notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
