# Generated by Django 6.0.4 on 2026-08-19 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickentry', '0002_manualentry_unmapped_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='SitRepSignatoryConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prepared_by', models.CharField(default='Team Charlie', max_length=255)),
                ('noted_by', models.CharField(default='NIEL A. PARCO', max_length=255)),
                ('noted_by_title', models.CharField(default='Operations and Warning Division Head', max_length=255)),
                ('approved_by', models.CharField(default='DR. MELCHOR P. AVENILLA, JR.', max_length=255)),
                ('approved_by_title', models.CharField(default='PGDH - PDRRMC', max_length=255)),
            ],
            options={
                'verbose_name': 'SitRep Signatory Configuration',
                'verbose_name_plural': 'SitRep Signatory Configuration',
            },
        ),
    ]
