# Generated by Django 6.0.4 on 2026-08-19 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickentry', '0003_sitrepsignatoryconfig'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manualbatch',
            name='generated_pdf',
        ),
        migrations.AddField(
            model_name='manualbatch',
            name='actions_taken',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='manualbatch',
            name='approved_by',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='manualbatch',
            name='approved_by_title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='manualbatch',
            name='noted_by',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='manualbatch',
            name='noted_by_title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='manualbatch',
            name='prepared_by',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='manualbatch',
            name='synopsis',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='manualbatch',
            name='weather_conditions',
            field=models.TextField(blank=True, default=''),
        ),
    ]
