# Generated by Django 6.0.4 on 2026-08-20 09:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickentry', '0004_remove_manualbatch_generated_pdf_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='manualbatch',
            name='amended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='manualbatch',
            name='amended_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amended_batches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='manualbatch',
            name='amendment_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
