# Generated by Django 6.0.4 on 2026-08-20 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickentry', '0005_manualbatch_amended_at_manualbatch_amended_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manualentry',
            options={'ordering': ['municipality', 'processed_at', 'id'], 'verbose_name_plural': 'Manual Entries'},
        ),
        migrations.AlterUniqueTogether(
            name='manualentry',
            unique_together=set(),
        ),
    ]
