# Generated by Django 6.0.4 on 2026-08-20 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickentry', '0007_fireincident_cause_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualentry',
            name='weather_condition',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
