# Generated by Django 6.0.4 on 2026-08-26 18:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickentry', '0008_manualentry_weather_condition'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchAmendment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amended_at', models.DateTimeField()),
                ('amendment_reason', models.TextField()),
                ('amended_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batch_amendments', to=settings.AUTH_USER_MODEL)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amendment_log', to='quickentry.manualbatch')),
            ],
            options={
                'verbose_name': 'Batch Amendment',
                'verbose_name_plural': 'Batch Amendments',
                'ordering': ['amended_at', 'id'],
            },
        ),
    ]
